### ISSUE TITLE
links in readme don't work

### ISSUE THREAD

**Issue by TimDaub** [strikedao/strikedao.com#156]
these 

[](https://github.com/strikedao/strikedao.com#context--documentation--license)[context](https://github.com/strikedao/strikedao.com/blob/main/readme.md#context) | [documentation](https://github.com/strikedao/strikedao.com/blob/main/readme.md#documentation) | [license](https://github.com/strikedao/strikedao.com/blob/main/readme.md/#license)

**Comment by EddieCornelious** [comment]
#157
